### ISSUE TITLE
A Wiki for resources

### ISSUE THREAD

**Issue by thedrow** [tknerr/vagrant-plugin-bundler#12]
Not long ago I wrote a blog post in order to promote vagrant plugin bundler but there is no way to add it somewhere since the wiki seems to be empty.
I suggest that we open the wiki and add a community resources page so everyone can share their experience with this plugin.
Also a referral to the wiki should be added in the README file.

[Here is the blog post](https://omerkatz.com/blog/2013/6/19/manage-your-vagrant-plugins-requirements-with-vagrant-plugin-bundler)

**Comment by tknerr** [comment]
Hey cool, thanks man! :-)

The Wiki feature is be enabled, so feel free to create a new Wiki page for that. 

I can add it to the README for sure - or even better would be if you send me a pull request

**Comment by tknerr** [comment]
Thanks!
